# Generated by Django 3.2.7 on 2021-09-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_rename_requestdata_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='uuid',
            field=models.TextField(null=True),
        ),
    ]
